// src/shared/mock-db/seed/cms.seed.ts
/** Единый сид постов и баннеров админки (источник для MockDbSnapshot.cms и re-export в фичах). */

import type { AdminManagedBanner, AdminManagedPost } from '@/features/admin-posts-banners-management/model/types';

export const SEED_CMS_POSTS: AdminManagedPost[] = [
  {
    id: 'admin-post-1',
    title: 'Как подготовить питомца к первой передержке',
    content:
      'Передержка может стать стрессом для животного, если его не подготовить заранее. Познакомьте питомца с ситтером до заселения, передайте привычные вещи, составьте понятный режим прогулок и кормления, а также заранее расскажите о реакциях питомца на чужих людей, шум и новую обстановку.',
    imageUrls: ['/images/post-1.png'],
    coverImageUrl: '/images/post-1.png',
    tags: ['уход', 'передержка'],
    status: 'published',
    publishedAt: '2026-02-20T10:00:00.000Z',
    createdAt: '2026-02-19T18:00:00.000Z',
    updatedAt: '2026-02-20T10:00:00.000Z',
  },
  {
    id: 'admin-post-2',
    title: '5 признаков хорошего петситтера',
    content:
      'Хороший петситтер задаёт уточняющие вопросы, внимательно относится к режиму питомца, умеет присылать понятные отчёты и знает базовые правила безопасности. Для владельца это означает предсказуемость, спокойствие и доверие к специалисту.',
    imageUrls: [],
    coverImageUrl: undefined,
    tags: ['советы'],
    status: 'published',
    publishedAt: '2026-02-18T14:30:00.000Z',
    createdAt: '2026-02-18T10:30:00.000Z',
    updatedAt: '2026-02-18T14:30:00.000Z',
  },
  {
    id: 'admin-post-3',
    title: 'Новый раздел с рекомендациями для владельцев',
    content:
      'Мы готовим отдельную подборку материалов для владельцев животных: инструкции, памятки, чек-листы и советы по взаимодействию со специалистами. Материал находится в черновике и будет опубликован после финальной редакторской проверки.',
    imageUrls: ['/images/post-3.png', '/images/post-3-extra.png'],
    coverImageUrl: '/images/post-3.png',
    tags: ['новости', 'платформа'],
    status: 'draft',
    createdAt: '2026-03-10T09:00:00.000Z',
    updatedAt: '2026-03-10T09:00:00.000Z',
  },
  {
    id: 'admin-post-4',
    title: 'Зимняя прогулка с собакой: что учесть',
    content:
      'В холодное время года короче дневной свет, скользкие поверхности и сухой воздух. Используйте видимую амуницию, проверяйте лапы после прогулки, не перегружайте питомца и при необходимости сокращайте время на улице. Если собака старше или с заболеваниями суставов — согласуйте нагрузку с ветеринаром.',
    imageUrls: ['/images/post-5.png'],
    coverImageUrl: '/images/post-5.png',
    tags: ['собаки', 'прогулка', 'зима'],
    status: 'published',
    publishedAt: '2026-03-15T11:00:00.000Z',
    createdAt: '2026-03-14T10:00:00.000Z',
    updatedAt: '2026-03-15T11:00:00.000Z',
  },
  {
    id: 'admin-post-5',
    title: 'Аптечка для питомца при передержке',
    content:
      'Составьте список лекарств с дозировкой и временем приёма, оставьте контакт ветклиники и историю аллергий. Добавьте средства от паразитов, перевязочный материал и то, без чего питомец не может обойтись сутки — например специальный корм или добавки.',
    imageUrls: ['/images/post-1.png'],
    coverImageUrl: '/images/post-1.png',
    tags: ['уход', 'здоровье', 'передержка'],
    status: 'published',
    publishedAt: '2026-03-16T08:30:00.000Z',
    createdAt: '2026-03-15T14:00:00.000Z',
    updatedAt: '2026-03-16T08:30:00.000Z',
  },
  {
    id: 'admin-post-6',
    title: 'Как читать сигналы стресса у кошки',
    content:
      'Прижатые уши, дёргание хвостом, напряжённая поза, избегание контакта — кошка просит паузы. Не настаивайте на общении, дайте укрытие и спокойную обстановку. Со временем животное привыкнет к новому человеку, если режим предсказуем и нет навязчивых действий.',
    imageUrls: ['/images/post-3.png'],
    coverImageUrl: '/images/post-3.png',
    tags: ['кошки', 'поведение'],
    status: 'published',
    publishedAt: '2026-03-17T12:00:00.000Z',
    createdAt: '2026-03-16T18:00:00.000Z',
    updatedAt: '2026-03-17T12:00:00.000Z',
  },
  {
    id: 'admin-post-7',
    title: 'Знакомство двух животных: пошагово',
    content:
      'Начните с раздельных комнат и обмена запахами через перегородку. Первые встречи — короткие, под присмотром, без конкуренции за еду и лежанки. Награды за спокойное поведение ускоряют привыкание; при агрессии разводите питомцев и возвращайтесь к более медленному сценарию.',
    imageUrls: [],
    coverImageUrl: undefined,
    tags: ['советы', 'поведение'],
    status: 'published',
    publishedAt: '2026-03-18T09:15:00.000Z',
    createdAt: '2026-03-17T11:00:00.000Z',
    updatedAt: '2026-03-18T09:15:00.000Z',
  },
  {
    id: 'admin-post-8',
    title: 'Питание в дороге: контейнеры и вода',
    content:
      'Берите привычный корм порциями на каждый день, используйте герметичные контейнеры и не меняйте рацион резко в поездке. Вода в дороге — часто небольшими порциями, чтобы снизить риск укачивания. Для длинных переездов заранее спланируйте остановки и тень летом.',
    imageUrls: ['/images/post-5.png'],
    coverImageUrl: '/images/post-5.png',
    tags: ['путешествия', 'уход'],
    status: 'published',
    publishedAt: '2026-03-19T07:45:00.000Z',
    createdAt: '2026-03-18T16:20:00.000Z',
    updatedAt: '2026-03-19T07:45:00.000Z',
  },
  {
    id: 'admin-post-9',
    title: 'Документы и ветпаспорт перед выездом',
    content:
      'Проверьте сроки прививок и отметки о обработке от паразитов. Для поездок за границу могут понадобиться дополнительные сертификаты — уточняйте правила заранее. Сохраните контакты ветеринара и копии документов в облаке на случай потери бумажной версии.',
    imageUrls: [],
    coverImageUrl: undefined,
    tags: ['советы', 'документы'],
    status: 'published',
    publishedAt: '2026-03-20T10:20:00.000Z',
    createdAt: '2026-03-19T20:00:00.000Z',
    updatedAt: '2026-03-20T10:20:00.000Z',
  },
];

export const SEED_CMS_BANNERS: AdminManagedBanner[] = [
  {
    id: 'banner-1',
    title: 'Найдите проверенного петситтера рядом',
    description: 'Главный баннер на главной странице с переходом в поиск специалистов.',
    imageUrl: '/images/banner-home-hero.png',
    linkUrl: '/services?service=boarding',
    linkTarget: 'specialists',
    placement: 'home_hero',
    status: 'published',
    startsAt: '2026-03-01T00:00:00.000Z',
    createdAt: '2026-03-01T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'banner-home-post-4',
    title: 'Зимние прогулки: безопасность и комфорт',
    description: 'Короткая памятка для владельцев собак в холодный сезон.',
    imageUrl: '/images/banner-posts.png',
    linkUrl: '/posts/admin-post-4',
    linkTarget: 'posts',
    linkedPostId: 'admin-post-4',
    placement: 'home_hero',
    status: 'published',
    startsAt: '2026-03-14T00:00:00.000Z',
    createdAt: '2026-03-14T09:00:00.000Z',
    updatedAt: '2026-03-14T09:00:00.000Z',
  },
  {
    id: 'banner-home-post-5',
    title: 'Соберите аптечку перед передержкой',
    description: 'Что положить в дорожный набор для питомца — в статье.',
    imageUrl: '/images/banner-specialists.png',
    linkUrl: '/posts/admin-post-5',
    linkTarget: 'posts',
    linkedPostId: 'admin-post-5',
    placement: 'home_hero',
    status: 'published',
    startsAt: '2026-03-15T00:00:00.000Z',
    createdAt: '2026-03-15T10:00:00.000Z',
    updatedAt: '2026-03-15T10:00:00.000Z',
  },
  {
    id: 'banner-2',
    title: 'Полезные статьи по уходу за питомцами',
    description: 'Баннер внутри раздела постов для повышения просмотров публикаций.',
    imageUrl: '/images/banner-posts.png',
    linkUrl: '/posts/admin-post-1',
    linkTarget: 'posts',
    linkedPostId: 'admin-post-1',
    placement: 'posts',
    status: 'published',
    startsAt: '2026-03-05T00:00:00.000Z',
    createdAt: '2026-03-04T12:00:00.000Z',
    updatedAt: '2026-03-05T00:00:00.000Z',
  },
  {
    id: 'banner-3',
    title: 'Весенний спецпроект',
    description: 'Черновой баннер для будущей кампании в каталоге специалистов.',
    imageUrl: '/images/banner-specialists.png',
    linkUrl: '/specialists',
    linkTarget: 'specialists',
    placement: 'specialists',
    status: 'draft',
    createdAt: '2026-03-12T13:20:00.000Z',
    updatedAt: '2026-03-12T13:20:00.000Z',
  },
];
